
project_id = "jdqsgigwbcukxijiunwl"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
ip_version = "ipv6"
tenant_id = "realtime-dev"

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1:54321"

[inbucket]
enabled = true
port = 54324
sender_name = "Supabase"
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
port = 54327
file_size_limit = "50MiB"
image_transformation = {enabled = true}

[auth]
enabled = true
port = 54328
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = []
jwt_expiry = 3600
enable_signup = true
enable_confirmations = false

[auth.external.github]
enabled = false
client_id = "env(GITHUB_CLIENT_ID)"
secret = "env(GITHUB_SECRET)"
redirect_uri = "http://127.0.0.1:54321/auth/v1/callback"

[functions.ai-evaluation]
verify_jwt = false

[functions.ai-feedback]
verify_jwt = false

[functions.comprehensive-evaluation]
verify_jwt = false

[functions.google-sheets-proxy]
verify_jwt = false

[functions.typeform-webhook]
verify_jwt = false

[analytics]
enabled = false
port = 54327
vector_port = 54328
backend = "postgres"
