
-- First, clear any existing data to ensure clean population
DELETE FROM public.country_codes;

-- Insert comprehensive list of all countries with their codes, ISO codes, and flag emojis
INSERT INTO public.country_codes (country_name, country_code, iso_code, country_flag_emoji, is_active) VALUES
('Afghanistan', '+93', 'AF', '🇦🇫', true),
('Albania', '+355', 'AL', '🇦🇱', true),
('Algeria', '+213', 'DZ', '🇩🇿', true),
('American Samoa', '+1684', 'AS', '🇦🇸', true),
('Andorra', '+376', 'AD', '🇦🇩', true),
('Angola', '+244', 'AO', '🇦🇴', true),
('Anguilla', '+1264', 'AI', '🇦🇮', true),
('Antarctica', '+672', 'AQ', '🇦🇶', true),
('Antigua and Barbuda', '+1268', 'AG', '🇦🇬', true),
('Argentina', '+54', 'AR', '🇦🇷', true),
('Armenia', '+374', 'AM', '🇦🇲', true),
('Aruba', '+297', 'AW', '🇦🇼', true),
('Australia', '+61', 'AU', '🇦🇺', true),
('Austria', '+43', 'AT', '🇦🇹', true),
('Azerbaijan', '+994', 'AZ', '🇦🇿', true),
('Bahamas', '+1242', 'BS', '🇧🇸', true),
('Bahrain', '+973', 'BH', '🇧🇭', true),
('Bangladesh', '+880', 'BD', '🇧🇩', true),
('Barbados', '+1246', 'BB', '🇧🇧', true),
('Belarus', '+375', 'BY', '🇧🇾', true),
('Belgium', '+32', 'BE', '🇧🇪', true),
('Belize', '+501', 'BZ', '🇧🇿', true),
('Benin', '+229', 'BJ', '🇧🇯', true),
('Bermuda', '+1441', 'BM', '🇧🇲', true),
('Bhutan', '+975', 'BT', '🇧🇹', true),
('Bolivia', '+591', 'BO', '🇧🇴', true),
('Bosnia and Herzegovina', '+387', 'BA', '🇧🇦', true),
('Botswana', '+267', 'BW', '🇧🇼', true),
('Brazil', '+55', 'BR', '🇧🇷', true),
('British Virgin Islands', '+1284', 'VG', '🇻🇬', true),
('Brunei', '+673', 'BN', '🇧🇳', true),
('Bulgaria', '+359', 'BG', '🇧🇬', true),
('Burkina Faso', '+226', 'BF', '🇧🇫', true),
('Burundi', '+257', 'BI', '🇧🇮', true),
('Cambodia', '+855', 'KH', '🇰🇭', true),
('Cameroon', '+237', 'CM', '🇨🇲', true),
('Canada', '+1', 'CA', '🇨🇦', true),
('Cape Verde', '+238', 'CV', '🇨🇻', true),
('Cayman Islands', '+1345', 'KY', '🇰🇾', true),
('Central African Republic', '+236', 'CF', '🇨🇫', true),
('Chad', '+235', 'TD', '🇹🇩', true),
('Chile', '+56', 'CL', '🇨🇱', true),
('China', '+86', 'CN', '🇨🇳', true),
('Christmas Island', '+61', 'CX', '🇨🇽', true),
('Cocos Islands', '+61', 'CC', '🇨🇨', true),
('Colombia', '+57', 'CO', '🇨🇴', true),
('Comoros', '+269', 'KM', '🇰🇲', true),
('Congo', '+242', 'CG', '🇨🇬', true),
('Democratic Republic of Congo', '+243', 'CD', '🇨🇩', true),
('Cook Islands', '+682', 'CK', '🇨🇰', true),
('Costa Rica', '+506', 'CR', '🇨🇷', true),
('Croatia', '+385', 'HR', '🇭🇷', true),
('Cuba', '+53', 'CU', '🇨🇺', true),
('Cyprus', '+357', 'CY', '🇨🇾', true),
('Czech Republic', '+420', 'CZ', '🇨🇿', true),
('Denmark', '+45', 'DK', '🇩🇰', true),
('Djibouti', '+253', 'DJ', '🇩🇯', true),
('Dominica', '+1767', 'DM', '🇩🇲', true),
('Dominican Republic', '+1809', 'DO', '🇩🇴', true),
('East Timor', '+670', 'TL', '🇹🇱', true),
('Ecuador', '+593', 'EC', '🇪🇨', true),
('Egypt', '+20', 'EG', '🇪🇬', true),
('El Salvador', '+503', 'SV', '🇸🇻', true),
('Equatorial Guinea', '+240', 'GQ', '🇬🇶', true),
('Eritrea', '+291', 'ER', '🇪🇷', true),
('Estonia', '+372', 'EE', '🇪🇪', true),
('Ethiopia', '+251', 'ET', '🇪🇹', true),
('Falkland Islands', '+500', 'FK', '🇫🇰', true),
('Faroe Islands', '+298', 'FO', '🇫🇴', true),
('Fiji', '+679', 'FJ', '🇫🇯', true),
('Finland', '+358', 'FI', '🇫🇮', true),
('France', '+33', 'FR', '🇫🇷', true),
('French Guiana', '+594', 'GF', '🇬🇫', true),
('French Polynesia', '+689', 'PF', '🇵🇫', true),
('Gabon', '+241', 'GA', '🇬🇦', true),
('Gambia', '+220', 'GM', '🇬🇲', true),
('Georgia', '+995', 'GE', '🇬🇪', true),
('Germany', '+49', 'DE', '🇩🇪', true),
('Ghana', '+233', 'GH', '🇬🇭', true),
('Gibraltar', '+350', 'GI', '🇬🇮', true),
('Greece', '+30', 'GR', '🇬🇷', true),
('Greenland', '+299', 'GL', '🇬🇱', true),
('Grenada', '+1473', 'GD', '🇬🇩', true),
('Guadeloupe', '+590', 'GP', '🇬🇵', true),
('Guam', '+1671', 'GU', '🇬🇺', true),
('Guatemala', '+502', 'GT', '🇬🇹', true),
('Guinea', '+224', 'GN', '🇬🇳', true),
('Guinea-Bissau', '+245', 'GW', '🇬🇼', true),
('Guyana', '+592', 'GY', '🇬🇾', true),
('Haiti', '+509', 'HT', '🇭🇹', true),
('Honduras', '+504', 'HN', '🇭🇳', true),
('Hong Kong', '+852', 'HK', '🇭🇰', true),
('Hungary', '+36', 'HU', '🇭🇺', true),
('Iceland', '+354', 'IS', '🇮🇸', true),
('India', '+91', 'IN', '🇮🇳', true),
('Indonesia', '+62', 'ID', '🇮🇩', true),
('Iran', '+98', 'IR', '🇮🇷', true),
('Iraq', '+964', 'IQ', '🇮🇶', true),
('Ireland', '+353', 'IE', '🇮🇪', true),
('Israel', '+972', 'IL', '🇮🇱', true),
('Italy', '+39', 'IT', '🇮🇹', true),
('Ivory Coast', '+225', 'CI', '🇨🇮', true),
('Jamaica', '+1876', 'JM', '🇯🇲', true),
('Japan', '+81', 'JP', '🇯🇵', true),
('Jordan', '+962', 'JO', '🇯🇴', true),
('Kazakhstan', '+7', 'KZ', '🇰🇿', true),
('Kenya', '+254', 'KE', '🇰🇪', true),
('Kiribati', '+686', 'KI', '🇰🇮', true),
('North Korea', '+850', 'KP', '🇰🇵', true),
('South Korea', '+82', 'KR', '🇰🇷', true),
('Kuwait', '+965', 'KW', '🇰🇼', true),
('Kyrgyzstan', '+996', 'KG', '🇰🇬', true),
('Laos', '+856', 'LA', '🇱🇦', true),
('Latvia', '+371', 'LV', '🇱🇻', true),
('Lebanon', '+961', 'LB', '🇱🇧', true),
('Lesotho', '+266', 'LS', '🇱🇸', true),
('Liberia', '+231', 'LR', '🇱🇷', true),
('Libya', '+218', 'LY', '🇱🇾', true),
('Liechtenstein', '+423', 'LI', '🇱🇮', true),
('Lithuania', '+370', 'LT', '🇱🇹', true),
('Luxembourg', '+352', 'LU', '🇱🇺', true),
('Macau', '+853', 'MO', '🇲🇴', true),
('Macedonia', '+389', 'MK', '🇲🇰', true),
('Madagascar', '+261', 'MG', '🇲🇬', true),
('Malawi', '+265', 'MW', '🇲🇼', true),
('Malaysia', '+60', 'MY', '🇲🇾', true),
('Maldives', '+960', 'MV', '🇲🇻', true),
('Mali', '+223', 'ML', '🇲🇱', true),
('Malta', '+356', 'MT', '🇲🇹', true),
('Marshall Islands', '+692', 'MH', '🇲🇭', true),
('Martinique', '+596', 'MQ', '🇲🇶', true),
('Mauritania', '+222', 'MR', '🇲🇷', true),
('Mauritius', '+230', 'MU', '🇲🇺', true),
('Mayotte', '+262', 'YT', '🇾🇹', true),
('Mexico', '+52', 'MX', '🇲🇽', true),
('Micronesia', '+691', 'FM', '🇫🇲', true),
('Moldova', '+373', 'MD', '🇲🇩', true),
('Monaco', '+377', 'MC', '🇲🇨', true),
('Mongolia', '+976', 'MN', '🇲🇳', true),
('Montenegro', '+382', 'ME', '🇲🇪', true),
('Montserrat', '+1664', 'MS', '🇲🇸', true),
('Morocco', '+212', 'MA', '🇲🇦', true),
('Mozambique', '+258', 'MZ', '🇲🇿', true),
('Myanmar', '+95', 'MM', '🇲🇲', true),
('Namibia', '+264', 'NA', '🇳🇦', true),
('Nauru', '+674', 'NR', '🇳🇷', true),
('Nepal', '+977', 'NP', '🇳🇵', true),
('Netherlands', '+31', 'NL', '🇳🇱', true),
('Netherlands Antilles', '+599', 'AN', '🇦🇳', true),
('New Caledonia', '+687', 'NC', '🇳🇨', true),
('New Zealand', '+64', 'NZ', '🇳🇿', true),
('Nicaragua', '+505', 'NI', '🇳🇮', true),
('Niger', '+227', 'NE', '🇳🇪', true),
('Nigeria', '+234', 'NG', '🇳🇬', true),
('Niue', '+683', 'NU', '🇳🇺', true),
('Norfolk Island', '+672', 'NF', '🇳🇫', true),
('Northern Mariana Islands', '+1670', 'MP', '🇲🇵', true),
('Norway', '+47', 'NO', '🇳🇴', true),
('Oman', '+968', 'OM', '🇴🇲', true),
('Pakistan', '+92', 'PK', '🇵🇰', true),
('Palau', '+680', 'PW', '🇵🇼', true),
('Palestine', '+970', 'PS', '🇵🇸', true),
('Panama', '+507', 'PA', '🇵🇦', true),
('Papua New Guinea', '+675', 'PG', '🇵🇬', true),
('Paraguay', '+595', 'PY', '🇵🇾', true),
('Peru', '+51', 'PE', '🇵🇪', true),
('Philippines', '+63', 'PH', '🇵🇭', true),
('Pitcairn', '+64', 'PN', '🇵🇳', true),
('Poland', '+48', 'PL', '🇵🇱', true),
('Portugal', '+351', 'PT', '🇵🇹', true),
('Puerto Rico', '+1787', 'PR', '🇵🇷', true),
('Qatar', '+974', 'QA', '🇶🇦', true),
('Reunion', '+262', 'RE', '🇷🇪', true),
('Romania', '+40', 'RO', '🇷🇴', true),
('Russia', '+7', 'RU', '🇷🇺', true),
('Rwanda', '+250', 'RW', '🇷🇼', true),
('Saint Helena', '+290', 'SH', '🇸🇭', true),
('Saint Kitts and Nevis', '+1869', 'KN', '🇰🇳', true),
('Saint Lucia', '+1758', 'LC', '🇱🇨', true),
('Saint Pierre and Miquelon', '+508', 'PM', '🇵🇲', true),
('Saint Vincent and the Grenadines', '+1784', 'VC', '🇻🇨', true),
('Samoa', '+685', 'WS', '🇼🇸', true),
('San Marino', '+378', 'SM', '🇸🇲', true),
('Sao Tome and Principe', '+239', 'ST', '🇸🇹', true),
('Saudi Arabia', '+966', 'SA', '🇸🇦', true),
('Senegal', '+221', 'SN', '🇸🇳', true),
('Serbia', '+381', 'RS', '🇷🇸', true),
('Seychelles', '+248', 'SC', '🇸🇨', true),
('Sierra Leone', '+232', 'SL', '🇸🇱', true),
('Singapore', '+65', 'SG', '🇸🇬', true),
('Slovakia', '+421', 'SK', '🇸🇰', true),
('Slovenia', '+386', 'SI', '🇸🇮', true),
('Solomon Islands', '+677', 'SB', '🇸🇧', true),
('Somalia', '+252', 'SO', '🇸🇴', true),
('South Africa', '+27', 'ZA', '🇿🇦', true),
('South Georgia and South Sandwich Islands', '+500', 'GS', '🇬🇸', true),
('Spain', '+34', 'ES', '🇪🇸', true),
('Sri Lanka', '+94', 'LK', '🇱🇰', true),
('Sudan', '+249', 'SD', '🇸🇩', true),
('Suriname', '+597', 'SR', '🇸🇷', true),
('Swaziland', '+268', 'SZ', '🇸🇿', true),
('Sweden', '+46', 'SE', '🇸🇪', true),
('Switzerland', '+41', 'CH', '🇨🇭', true),
('Syria', '+963', 'SY', '🇸🇾', true),
('Taiwan', '+886', 'TW', '🇹🇼', true),
('Tajikistan', '+992', 'TJ', '🇹🇯', true),
('Tanzania', '+255', 'TZ', '🇹🇿', true),
('Thailand', '+66', 'TH', '🇹🇭', true),
('Togo', '+228', 'TG', '🇹🇬', true),
('Tokelau', '+690', 'TK', '🇹🇰', true),
('Tonga', '+676', 'TO', '🇹🇴', true),
('Trinidad and Tobago', '+1868', 'TT', '🇹🇹', true),
('Tunisia', '+216', 'TN', '🇹🇳', true),
('Turkey', '+90', 'TR', '🇹🇷', true),
('Turkmenistan', '+993', 'TM', '🇹🇲', true),
('Turks and Caicos Islands', '+1649', 'TC', '🇹🇨', true),
('Tuvalu', '+688', 'TV', '🇹🇻', true),
('Uganda', '+256', 'UG', '🇺🇬', true),
('Ukraine', '+380', 'UA', '🇺🇦', true),
('United Arab Emirates', '+971', 'AE', '🇦🇪', true),
('United Kingdom', '+44', 'GB', '🇬🇧', true),
('United States', '+1', 'US', '🇺🇸', true),
('Uruguay', '+598', 'UY', '🇺🇾', true),
('Uzbekistan', '+998', 'UZ', '🇺🇿', true),
('Vanuatu', '+678', 'VU', '🇻🇺', true),
('Vatican City', '+379', 'VA', '🇻🇦', true),
('Venezuela', '+58', 'VE', '🇻🇪', true),
('Vietnam', '+84', 'VN', '🇻🇳', true),
('Virgin Islands', '+1340', 'VI', '🇻🇮', true),
('Wallis and Futuna', '+681', 'WF', '🇼🇫', true),
('Western Sahara', '+212', 'EH', '🇪🇭', true),
('Yemen', '+967', 'YE', '🇾🇪', true),
('Zambia', '+260', 'ZM', '🇿🇲', true),
('Zimbabwe', '+263', 'ZW', '🇿🇼', true);

-- Verify the insertion and count records
SELECT COUNT(*) as total_countries FROM public.country_codes;

-- Check for any missing flag emojis
SELECT country_name, country_code, iso_code, country_flag_emoji 
FROM public.country_codes 
WHERE country_flag_emoji IS NULL OR country_flag_emoji = '';
