// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jdqsgigwbcukxijiunwl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpkcXNnaWd3YmN1a3hpaml1bndsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzODA2NDcsImV4cCI6MjA2ODk1NjY0N30.QWqLMVIH_ej2A7shVjN-FEWzMA6uP0_L5w315Fxhx08";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});